sources:
  - name: Catalog
    handler:
      graphql:
        source: './catalog.gql'
        endpoint: 'http://localhost:8084/graphql'
        operationHeaders:
          x-api-key: "{context.headers['x-api-key']}"

additionalEnvelopPlugins: ./src/envelopPlugins.ts

additionalResolvers:
  - ./src/additionalResolvers.ts
