sources:
  - name: Catalog
    handler:
      graphql:
        source: '../catalog.gql'
        endpoint: '{env.CATALOG_URL}/graphql'
        operationHeaders:
          x-api-key: "{context.headers['x-api-key']}"
  - name: Catalog2
    handler:
      graphql:
        source: '../other.gql'
        endpoint: '{env.SECOND_URL}/graphql'
        operationHeaders:
          x-api-key: "{context.headers['x-api-key']}"

